-- ---------------------------------------------------
-- TABLE CREATION
-- ---------------------------------------------------

CREATE TABLE IF NOT EXISTS tb_user (
	id_user UUID,
	name VARCHAR(120) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	id_kitchen INTEGER,
	id_profile INTEGER NOT NULL,
	active BOOLEAN NOT NULL DEFAULT true,
	last_login TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_user)
);

CREATE TABLE IF NOT EXISTS tb_profile (
	id_profile INTEGER GENERATED BY DEFAULT AS IDENTITY,
	access_type VARCHAR(50) NOT NULL UNIQUE,
	description VARCHAR(255),
	PRIMARY KEY (id_profile)
);

CREATE TABLE IF NOT EXISTS tb_kitchen (
	id_kitchen INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(120) NOT NULL,
	code VARCHAR(20) NOT NULL UNIQUE,
	address VARCHAR(255),
	active BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_kitchen)
);

CREATE TABLE IF NOT EXISTS tb_product (
	id_product INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(150) NOT NULL,
	brand VARCHAR(80),
	id_category INTEGER,
	id_unit INTEGER NOT NULL,
	barcode VARCHAR(50) UNIQUE,
	photo_url VARCHAR(255),
	active BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_product)
);

CREATE TABLE IF NOT EXISTS tb_category (
	id_category INTEGER GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(80) NOT NULL UNIQUE,
	description VARCHAR(255),
	PRIMARY KEY (id_category)
);

CREATE TABLE IF NOT EXISTS tb_measurement_unit (
	id_unit INTEGER GENERATED BY DEFAULT AS IDENTITY,
	symbol VARCHAR(10) NOT NULL UNIQUE,
	description VARCHAR(60) NOT NULL,
	PRIMARY KEY (id_unit)
);

CREATE TABLE IF NOT EXISTS tb_product_supplier (
	id_product INTEGER NOT NULL,
	id_supplier INTEGER NOT NULL,
	supplier_code VARCHAR(50),
	reference_price DECIMAL(12,2),
	lead_time_days INTEGER,
	PRIMARY KEY (id_product, id_supplier)
);

CREATE TABLE IF NOT EXISTS tb_supplier (
	id_supplier INTEGER GENERATED BY DEFAULT AS IDENTITY,
	legal_name VARCHAR(150) NOT NULL,
	cnpj VARCHAR(18) NOT NULL UNIQUE,
	email VARCHAR(150),
	whatsapp VARCHAR(20),
	rating INTEGER,
	active BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_supplier)
);

CREATE TABLE IF NOT EXISTS tb_product_kitchen_parameter (
	id_product INTEGER NOT NULL,
	id_kitchen INTEGER NOT NULL,
	min_stock DECIMAL(12,3) NOT NULL DEFAULT 0,
	max_stock DECIMAL(12,3),
	average_daily_consumption DECIMAL(12,3),
	PRIMARY KEY (id_product, id_kitchen)
);

CREATE TABLE IF NOT EXISTS tb_stock_batch (
	id_batch INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_product INTEGER NOT NULL,
	id_kitchen INTEGER NOT NULL,
	id_supplier INTEGER,
	batch_number VARCHAR(50) NOT NULL,
	invoice_number VARCHAR(50),
	initial_quantity DECIMAL(12,3) NOT NULL,
	current_quantity DECIMAL(12,3) NOT NULL,
	entry_date DATE NOT NULL,
	expiration_date DATE,
	unit_price DECIMAL(12,2),
	status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	PRIMARY KEY (id_batch)
);

CREATE TABLE IF NOT EXISTS tb_requisition (
	id_requisition INTEGER GENERATED BY DEFAULT AS IDENTITY,
	requisition_type VARCHAR(20) NOT NULL,
	origin VARCHAR(20) NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'UNDER_REVIEW',
	reason VARCHAR(255),
	id_kitchen INTEGER NOT NULL,
	id_requester_user UUID NOT NULL,
	id_approver_user UUID,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	approved_at TIMESTAMP,
	PRIMARY KEY (id_requisition)
);

CREATE TABLE IF NOT EXISTS tb_requisition_item (
	id_requisition_item INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_requisition INTEGER NOT NULL,
	id_product INTEGER NOT NULL,
	id_suggested_supplier INTEGER,
	quantity DECIMAL(12,3) NOT NULL,
	estimated_price DECIMAL(12,2),
	note VARCHAR(255),
	PRIMARY KEY (id_requisition_item)
);

CREATE TABLE IF NOT EXISTS tb_inventory (
	id_inventory INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_kitchen INTEGER NOT NULL,
	id_responsible_user UUID NOT NULL,
	started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	closed_at TIMESTAMP,
	status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
	note VARCHAR(255),
	PRIMARY KEY (id_inventory)
);

CREATE TABLE IF NOT EXISTS tb_inventory_count (
	id_count INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_inventory INTEGER NOT NULL,
	id_batch INTEGER NOT NULL,
	registered_quantity DECIMAL(12,3) NOT NULL,
	physical_quantity DECIMAL(12,3) NOT NULL,
	divergence DECIMAL(12,3),
	note VARCHAR(255),
	PRIMARY KEY (id_count)
);

CREATE TABLE IF NOT EXISTS tb_alert (
	id_alert INTEGER GENERATED BY DEFAULT AS IDENTITY,
	type VARCHAR(30) NOT NULL,
	severity VARCHAR(10) NOT NULL,
	id_batch INTEGER,
	id_product INTEGER,
	id_kitchen INTEGER NOT NULL,
	message VARCHAR(255) NOT NULL,
	is_read BOOLEAN NOT NULL DEFAULT false,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_alert)
);


-- ---------------------------------------------------
-- FOREIGN KEYS
-- ---------------------------------------------------

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_profile') THEN	
		ALTER TABLE tb_user
		ADD CONSTRAINT fk_user_profile
		FOREIGN KEY (id_profile) REFERENCES tb_profile (id_profile)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_kitchen') THEN
		ALTER TABLE tb_user
		ADD CONSTRAINT fk_user_kitchen
		FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_product_category') THEN
		ALTER TABLE tb_product
		ADD CONSTRAINT fk_product_category
		FOREIGN KEY (id_category) REFERENCES tb_category (id_category)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_product_unit') THEN
		ALTER TABLE tb_product
		ADD CONSTRAINT fk_product_unit
		FOREIGN KEY (id_unit) REFERENCES tb_measurement_unit (id_unit)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_productsupplier_product') THEN
		ALTER TABLE tb_product_supplier
		ADD CONSTRAINT fk_productsupplier_product
		FOREIGN KEY (id_product) REFERENCES tb_product (id_product)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_productsupplier_supplier') THEN
		ALTER TABLE tb_product_supplier
		ADD CONSTRAINT fk_productsupplier_supplier
		FOREIGN KEY (id_supplier) REFERENCES tb_supplier (id_supplier)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_parameter_product') THEN
		ALTER TABLE tb_product_kitchen_parameter
		ADD CONSTRAINT fk_parameter_product
		FOREIGN KEY (id_product) REFERENCES tb_product (id_product)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_parameter_kitchen') THEN
		ALTER TABLE tb_product_kitchen_parameter
		ADD CONSTRAINT fk_parameter_kitchen
		FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_batch_product') THEN
		ALTER TABLE tb_stock_batch
		ADD CONSTRAINT fk_batch_product
		FOREIGN KEY (id_product) REFERENCES tb_product (id_product)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_batch_kitchen') THEN
		ALTER TABLE tb_stock_batch
		ADD CONSTRAINT fk_batch_kitchen
		FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_batch_supplier') THEN
		ALTER TABLE tb_stock_batch
		ADD CONSTRAINT fk_batch_supplier
		FOREIGN KEY (id_supplier) REFERENCES tb_supplier (id_supplier)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisition_kitchen') THEN
		ALTER TABLE tb_requisition
		ADD CONSTRAINT fk_requisition_kitchen
		FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisition_requester_user') THEN
		ALTER TABLE tb_requisition
		ADD CONSTRAINT fk_requisition_requester_user
		FOREIGN KEY (id_requester_user) REFERENCES tb_user (id_user)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisition_approver_user') THEN
		ALTER TABLE tb_requisition
		ADD CONSTRAINT fk_requisition_approver_user
		FOREIGN KEY (id_approver_user) REFERENCES tb_user (id_user)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisitionitem_requisition') THEN
		ALTER TABLE tb_requisition_item
		ADD CONSTRAINT fk_requisitionitem_requisition
		FOREIGN KEY (id_requisition) REFERENCES tb_requisition (id_requisition)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisitionitem_product') THEN
		ALTER TABLE tb_requisition_item
		ADD CONSTRAINT fk_requisitionitem_product
		FOREIGN KEY (id_product) REFERENCES tb_product (id_product)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_requisitionitem_supplier') THEN
		ALTER TABLE tb_requisition_item
		ADD CONSTRAINT fk_requisitionitem_supplier
		FOREIGN KEY (id_suggested_supplier) REFERENCES tb_supplier (id_supplier)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_inventory_kitchen') THEN
		ALTER TABLE tb_inventory
		ADD CONSTRAINT fk_inventory_kitchen
		FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_inventory_user') THEN
		ALTER TABLE tb_inventory
		ADD CONSTRAINT fk_inventory_user
		FOREIGN KEY (id_responsible_user) REFERENCES tb_user (id_user)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_count_inventory') THEN
		ALTER TABLE tb_inventory_count
		ADD CONSTRAINT fk_count_inventory
		FOREIGN KEY (id_inventory) REFERENCES tb_inventory (id_inventory)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_count_batch') THEN
		ALTER TABLE tb_inventory_count
		ADD CONSTRAINT fk_count_batch
		FOREIGN KEY (id_batch) REFERENCES tb_stock_batch (id_batch)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alert_kitchen') THEN
		ALTER TABLE tb_alert
		ADD CONSTRAINT fk_alert_kitchen
		FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alert_product') THEN
		ALTER TABLE tb_alert
		ADD CONSTRAINT fk_alert_product
		FOREIGN KEY (id_product) REFERENCES tb_product (id_product)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alert_batch') THEN
		ALTER TABLE tb_alert
		ADD CONSTRAINT fk_alert_batch
		FOREIGN KEY (id_batch) REFERENCES tb_stock_batch (id_batch)
		ON UPDATE NO ACTION ON DELETE NO ACTION;
	END IF;
END;		
$$;

-- ---------------------------------------------------
-- CHECK CONSTRAINTS
-- ---------------------------------------------------

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_supplier_rating') THEN
		ALTER TABLE tb_supplier
		ADD CONSTRAINT ck_supplier_rating 
		CHECK (rating BETWEEN 1 AND 5);
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_batch_status') THEN
		ALTER TABLE tb_stock_batch
		ADD CONSTRAINT ck_batch_status 
		CHECK (status IN ('ACTIVE', 'WRITTEN_OFF', 'EXPIRED', 'CANCELLED'));
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_requisition_status') THEN
		ALTER TABLE tb_requisition
		ADD CONSTRAINT ck_requisition_status 
		CHECK (status IN ('UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED'));
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_requisition_type') THEN
		ALTER TABLE tb_requisition
		ADD CONSTRAINT ck_requisition_type 
		CHECK (requisition_type IN ('PURCHASE', 'TRANSFER', 'CONSUMPTION'));
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_inventory_status') THEN
		ALTER TABLE tb_inventory
		ADD CONSTRAINT ck_inventory_status 
		CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED'));
	END IF;
END;
$$;		

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_alert_severity') THEN
		ALTER TABLE tb_alert
		ADD CONSTRAINT ck_alert_severity 
		CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));
	END IF;
END;
$$;		

-- ---------------------------------------------------
-- INDEX CREATION
-- ---------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_user_profile 
ON tb_user (id_profile);

CREATE INDEX IF NOT EXISTS idx_user_kitchen 
ON tb_user (id_kitchen);

CREATE INDEX IF NOT EXISTS idx_user_email 
ON tb_user (email);

CREATE INDEX IF NOT EXISTS idx_user_active 
ON tb_user (active);

CREATE INDEX IF NOT EXISTS idx_product_category 
ON tb_product (id_category);

CREATE INDEX IF NOT EXISTS idx_product_unit 
ON tb_product (id_unit);

CREATE INDEX IF NOT EXISTS idx_product_barcode 
ON tb_product (barcode);

CREATE INDEX IF NOT EXISTS idx_product_active 
ON tb_product (active);

CREATE INDEX IF NOT EXISTS idx_productsupplier_product 
ON tb_product_supplier (id_product);

CREATE INDEX IF NOT EXISTS idx_productsupplier_supplier 
ON tb_product_supplier (id_supplier);

CREATE INDEX IF NOT EXISTS idx_parameter_product 
ON tb_product_kitchen_parameter (id_product);

CREATE INDEX IF NOT EXISTS idx_parameter_kitchen 
ON tb_product_kitchen_parameter (id_kitchen);

CREATE INDEX IF NOT EXISTS idx_batch_product 
ON tb_stock_batch (id_product);

CREATE INDEX IF NOT EXISTS idx_batch_kitchen 
ON tb_stock_batch (id_kitchen);

CREATE INDEX IF NOT EXISTS idx_batch_supplier 
ON tb_stock_batch (id_supplier);

CREATE INDEX IF NOT EXISTS idx_batch_status 
ON tb_stock_batch (status);

CREATE INDEX IF NOT EXISTS idx_batch_expiration_date 
ON tb_stock_batch (expiration_date);

CREATE INDEX IF NOT EXISTS idx_requisition_kitchen 
ON tb_requisition (id_kitchen);

CREATE INDEX IF NOT EXISTS idx_requisition_requester_user 
ON tb_requisition (id_requester_user);

CREATE INDEX IF NOT EXISTS idx_requisition_approver_user 
ON tb_requisition (id_approver_user);

CREATE INDEX IF NOT EXISTS idx_requisition_status 
ON tb_requisition (status);

CREATE INDEX IF NOT EXISTS idx_requisition_created_at 
ON tb_requisition (created_at);

CREATE INDEX IF NOT EXISTS idx_requisitionitem_requisition 
ON tb_requisition_item (id_requisition);

CREATE INDEX IF NOT EXISTS idx_requisitionitem_product 
ON tb_requisition_item (id_product);

CREATE INDEX IF NOT EXISTS idx_requisitionitem_supplier 
ON tb_requisition_item (id_suggested_supplier);

CREATE INDEX IF NOT EXISTS idx_inventory_kitchen 
ON tb_inventory (id_kitchen);

CREATE INDEX IF NOT EXISTS idx_inventory_user 
ON tb_inventory (id_responsible_user);

CREATE INDEX IF NOT EXISTS idx_inventory_status 
ON tb_inventory (status);

CREATE INDEX IF NOT EXISTS idx_count_inventory 
ON tb_inventory_count (id_inventory);

CREATE INDEX IF NOT EXISTS idx_count_batch 
ON tb_inventory_count (id_batch);

CREATE INDEX IF NOT EXISTS idx_alert_kitchen 
ON tb_alert (id_kitchen);

CREATE INDEX IF NOT EXISTS idx_alert_product 
ON tb_alert (id_product);

CREATE INDEX IF NOT EXISTS idx_alert_batch 
ON tb_alert (id_batch);

CREATE INDEX IF NOT EXISTS idx_alert_is_read 
ON tb_alert (is_read);

CREATE INDEX IF NOT EXISTS idx_alert_severity 
ON tb_alert (severity);

CREATE INDEX IF NOT EXISTS idx_alert_created_at 
ON tb_alert (created_at);

CREATE INDEX IF NOT EXISTS idx_batch_kitchen_status_expiration
ON tb_stock_batch (id_kitchen, status, expiration_date);

CREATE INDEX IF NOT EXISTS idx_requisition_status_created_at
ON tb_requisition (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_productsupplier_product_price
ON tb_product_supplier (id_product, reference_price);