-- ---------------------------------------------------
-- TABLE CREATION
-- ---------------------------------------------------

CREATE TABLE IF NOT EXISTS tb_profile (
    id_profile INTEGER GENERATED BY DEFAULT AS IDENTITY,
    access_type VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    PRIMARY KEY (id_profile)
    );

CREATE TABLE IF NOT EXISTS tb_kitchen (
    id_kitchen INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    address VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_kitchen)
    );

CREATE TABLE IF NOT EXISTS tb_user (
    id_user UUID,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(80),
    id_kitchen INTEGER,
    id_profile INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    last_login TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_user)
    );

CREATE TABLE IF NOT EXISTS tb_category (
    id_category INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(255),
    PRIMARY KEY (id_category)
    );

CREATE TABLE IF NOT EXISTS tb_measurement_unit (
    id_unit INTEGER GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(10) NOT NULL UNIQUE,
    description VARCHAR(60) NOT NULL,
    PRIMARY KEY (id_unit)
    );

CREATE TABLE IF NOT EXISTS tb_supplier (
    id_supplier INTEGER GENERATED BY DEFAULT AS IDENTITY,
    legal_name VARCHAR(150) NOT NULL,
    cnpj VARCHAR(18) NOT NULL UNIQUE,
    email VARCHAR(150),
    whatsapp VARCHAR(20),
    rating INTEGER,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_supplier)
    );

CREATE TABLE IF NOT EXISTS tb_product (
    id_product INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    brand VARCHAR(80),
    id_category INTEGER,
    id_unit INTEGER NOT NULL,
    barcode VARCHAR(50) UNIQUE,
    photo_url VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_product)
    );

CREATE TABLE IF NOT EXISTS tb_product_supplier (
    id_product INTEGER NOT NULL,
    id_supplier INTEGER NOT NULL,
    supplier_code VARCHAR(50),
    reference_price DECIMAL(12,2),
    lead_time_days INTEGER,
    PRIMARY KEY (id_product, id_supplier)
    );

CREATE TABLE IF NOT EXISTS tb_product_kitchen_parameter (
    id_product INTEGER NOT NULL,
    id_kitchen INTEGER NOT NULL,
    min_stock DECIMAL(12,3) NOT NULL DEFAULT 0,
    max_stock DECIMAL(12,3),
    average_daily_consumption DECIMAL(12,3),
    PRIMARY KEY (id_product, id_kitchen)
    );

CREATE TABLE IF NOT EXISTS tb_stock_batch (
    id_batch INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_product INTEGER NOT NULL,
    id_kitchen INTEGER NOT NULL,
    id_supplier INTEGER,
    batch_number VARCHAR(50) NOT NULL,
    invoice_number VARCHAR(50),
    initial_quantity DECIMAL(12,3) NOT NULL,
    current_quantity DECIMAL(12,3) NOT NULL,
    entry_date DATE NOT NULL,
    expiration_date DATE,
    unit_price DECIMAL(12,2),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    PRIMARY KEY (id_batch)
    );

CREATE TABLE IF NOT EXISTS tb_requisition (
    id_requisition INTEGER GENERATED BY DEFAULT AS IDENTITY,
    requisition_type VARCHAR(20) NOT NULL,
    origin VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'UNDER_REVIEW',
    reason VARCHAR(255),
    id_kitchen INTEGER NOT NULL,
    id_requester_user UUID NOT NULL,
    id_approver_user UUID,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP,
    PRIMARY KEY (id_requisition)
    );

CREATE TABLE IF NOT EXISTS tb_requisition_item (
    id_requisition_item INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_requisition INTEGER NOT NULL,
    id_product INTEGER NOT NULL,
    id_suggested_supplier INTEGER,
    quantity DECIMAL(12,3) NOT NULL,
    estimated_price DECIMAL(12,2),
    note VARCHAR(255),
    PRIMARY KEY (id_requisition_item)
    );

CREATE TABLE IF NOT EXISTS tb_inventory (
    id_inventory INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_kitchen INTEGER NOT NULL,
    id_responsible_user UUID NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    note VARCHAR(255),
    PRIMARY KEY (id_inventory)
    );

CREATE TABLE IF NOT EXISTS tb_inventory_count (
    id_count INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_inventory INTEGER NOT NULL,
    id_batch INTEGER NOT NULL,
    registered_quantity DECIMAL(12,3) NOT NULL,
    physical_quantity DECIMAL(12,3) NOT NULL,
    divergence DECIMAL(12,3),
    note VARCHAR(255),
    PRIMARY KEY (id_count)
    );

CREATE TABLE IF NOT EXISTS tb_alert (
    id_alert INTEGER GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(30) NOT NULL,
    severity VARCHAR(10) NOT NULL,
    id_batch INTEGER,
    id_product INTEGER,
    id_kitchen INTEGER NOT NULL,
    message VARCHAR(255) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_alert)
    );

-- ---------------------------------------------------
-- FOREIGN KEYS
-- ---------------------------------------------------

ALTER TABLE tb_user
    ADD CONSTRAINT fk_user_profile
        FOREIGN KEY (id_profile) REFERENCES tb_profile (id_profile)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_user
    ADD CONSTRAINT fk_user_kitchen
        FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_product
    ADD CONSTRAINT fk_product_category
        FOREIGN KEY (id_category) REFERENCES tb_category (id_category)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_product
    ADD CONSTRAINT fk_product_unit
        FOREIGN KEY (id_unit) REFERENCES tb_measurement_unit (id_unit)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_product_supplier
    ADD CONSTRAINT fk_productsupplier_product
        FOREIGN KEY (id_product) REFERENCES tb_product (id_product)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_product_supplier
    ADD CONSTRAINT fk_productsupplier_supplier
        FOREIGN KEY (id_supplier) REFERENCES tb_supplier (id_supplier)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_product_kitchen_parameter
    ADD CONSTRAINT fk_parameter_product
        FOREIGN KEY (id_product) REFERENCES tb_product (id_product)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_product_kitchen_parameter
    ADD CONSTRAINT fk_parameter_kitchen
        FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_stock_batch
    ADD CONSTRAINT fk_batch_product
        FOREIGN KEY (id_product) REFERENCES tb_product (id_product)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_stock_batch
    ADD CONSTRAINT fk_batch_kitchen
        FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_stock_batch
    ADD CONSTRAINT fk_batch_supplier
        FOREIGN KEY (id_supplier) REFERENCES tb_supplier (id_supplier)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_requisition
    ADD CONSTRAINT fk_requisition_kitchen
        FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_requisition
    ADD CONSTRAINT fk_requisition_requester_user
        FOREIGN KEY (id_requester_user) REFERENCES tb_user (id_user)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_requisition
    ADD CONSTRAINT fk_requisition_approver_user
        FOREIGN KEY (id_approver_user) REFERENCES tb_user (id_user)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_requisition_item
    ADD CONSTRAINT fk_requisitionitem_requisition
        FOREIGN KEY (id_requisition) REFERENCES tb_requisition (id_requisition)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_requisition_item
    ADD CONSTRAINT fk_requisitionitem_product
        FOREIGN KEY (id_product) REFERENCES tb_product (id_product)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_requisition_item
    ADD CONSTRAINT fk_requisitionitem_supplier
        FOREIGN KEY (id_suggested_supplier) REFERENCES tb_supplier (id_supplier)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_inventory
    ADD CONSTRAINT fk_inventory_kitchen
        FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_inventory
    ADD CONSTRAINT fk_inventory_user
        FOREIGN KEY (id_responsible_user) REFERENCES tb_user (id_user)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_inventory_count
    ADD CONSTRAINT fk_count_inventory
        FOREIGN KEY (id_inventory) REFERENCES tb_inventory (id_inventory)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_inventory_count
    ADD CONSTRAINT fk_count_batch
        FOREIGN KEY (id_batch) REFERENCES tb_stock_batch (id_batch)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_alert
    ADD CONSTRAINT fk_alert_kitchen
        FOREIGN KEY (id_kitchen) REFERENCES tb_kitchen (id_kitchen)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_alert
    ADD CONSTRAINT fk_alert_product
        FOREIGN KEY (id_product) REFERENCES tb_product (id_product)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tb_alert
    ADD CONSTRAINT fk_alert_batch
        FOREIGN KEY (id_batch) REFERENCES tb_stock_batch (id_batch)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

-- ---------------------------------------------------
-- CONSTRAINTS
-- ---------------------------------------------------

ALTER TABLE tb_supplier
    ADD CONSTRAINT ck_supplier_rating
        CHECK (rating BETWEEN 1 AND 5);

ALTER TABLE tb_stock_batch
    ADD CONSTRAINT ck_batch_status
        CHECK (status IN ('ACTIVE', 'WRITTEN_OFF', 'EXPIRED', 'CANCELLED'));

ALTER TABLE tb_requisition
    ADD CONSTRAINT ck_requisition_status
        CHECK (status IN ('UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED'));

ALTER TABLE tb_requisition
    ADD CONSTRAINT ck_requisition_type
        CHECK (requisition_type IN ('PURCHASE', 'TRANSFER', 'CONSUMPTION'));

ALTER TABLE tb_inventory
    ADD CONSTRAINT ck_inventory_status
        CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED'));

ALTER TABLE tb_alert
    ADD CONSTRAINT ck_alert_severity
        CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));
